blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog_pages.urls', namespace='blog_pages')),
    path('', include('login.urls')),
    path('perfiles/', include('perfiles.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blog_pages/urls.py
from django.urls import path
from blog_pages import views

app_name = 'blog_pages'

urlpatterns = [
    path('inicio/', views.inicio, name='inicio'),
    path('about/', views.acerca_de_mi, name='acerca_de_mi'),
    path('pages/', views.pages, name='leerpaginas'),
    path('pages/<pk>', views.leer_mas, name='leer_mas'),
    path('edit_page/<pk>', views.edit_page, name='edit_page'),
    path('delete_page/<pk>/', views.deletePage, name="delete_page"),
    path('create_page/', views.create_page, name="create_page"),
]

blog/login/urls.py
from django.urls import path
from login import views
from django.contrib.auth.views import LogoutView

app_name = 'login'

urlpatterns = [
    path('', views.login1, name='login'),
    path('error/', views.passornameincorrect, name='passornameincorrect'),
    path('register/', views.register, name='register'),
    path('logout/', LogoutView.as_view(template_name='login/logout.html'), name='logout'),
]

blog/perfiles/urls.py
from django.urls import path
from perfiles import views

app_name = 'perfiles'

urlpatterns = [
    path('perfil/', views.perfil, name='perfil'),
    path('editarPerfil/', views.editarPerfil, name='editarPerfil'),
]

blog/blog_pages/models.py
from django.db import models


class page(models.Model):
    title= models.CharField(max_length=30)
    subtitle=models.CharField(max_length=30)
    body=models.CharField(max_length=2000)
    author=models.CharField(max_length=30)
    date=models.DateField()
    image=models.ImageField(null=True, blank=True, upload_to="imagenes/")

    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
    
    def __str__(self):
        return f'{self.title}'

blog/login/models.py
from django.db import models

# Create your models here.

blog/perfiles/models.py
from django.db import models

# Create your models here.

blog/blog_pages/forms.py
from .models import page
from django.forms import ModelForm

class pageFormulario(ModelForm):
    class Meta:
        model = page
        fields = "__all__"

blog/login/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm 

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class UserRegisterForm(UserCreationForm):
    username= forms.CharField(max_length=50)
    email= forms.EmailField()
    password1 = forms.CharField(label='password1',widget=forms.PasswordInput)
    password2 = forms.CharField(label='password2',widget=forms.PasswordInput)

    class Meta:
        model =  User
        fields = ['username', 'email', 'password1', 'password2']

blog/perfiles/forms.py
from django import forms
from django.contrib.auth.models import User

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

blog/blog_pages/views.py
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from .forms import pageFormulario
from .models import page


@login_required
def inicio(request):
    return render(request,'blog_pages/inicio.html' )

def acerca_de_mi(request):
    return render(request,'blog_pages/acerca_de_mi.html' )

def pages(request):
    pages = page.objects.all()
    contexto = {"pages": pages}
    return render(request, "blog_pages/leerPaginas.html", contexto)

def leer_mas(request, pk):
    page_ = get_object_or_404(page, pk=pk)
    contexto = {"page": page_}
    return render(request, 'blog_pages/leer_mas.html', contexto)


@login_required
@staff_member_required
def edit_page(request, pk):
    page1 =page.objects.get(title=pk)
    if request.method == 'POST':
        miFormulario = pageFormulario(request.POST,request.FILES)
        print(miFormulario)
        
        if miFormulario.is_valid:
            informacion = miFormulario.cleaned_data
            
            page1.title = informacion['title']
            page1.subtitle = informacion['subtitle'] 
            page1.body = informacion['body']
            page1.author = informacion['author']
            page1.date = informacion['date']
            page1.image = informacion['image']
            page1.save()
            
            return render(request, "blog_pages/inicio.html")
        
    else:
        miFormulario = pageFormulario(initial={'title':page1.title, 
                                                   'subtitle':page1.subtitle, 
                                                   'body':page1.body, 
                                                   'author': page1.author,"date":page1.date,"image":page1.image})
        
    return render(request, "blog_pages/edit_page.html", {"miFormulario":miFormulario, "title":pk})

@login_required
@staff_member_required
def deletePage(request, pk):
    page1 = page.objects.get(title=pk)
    page1.delete()
    
    pages1 = page.objects.all()
    contexto= {"pages":pages1}
    return render(request, "blog_pages/leerPaginas.html", contexto)

@login_required
@staff_member_required
def create_page(request):
    if request.method == "POST":
        my_page = pageFormulario(request.POST,request.FILES)
        if my_page.is_valid():
            informacion = my_page.cleaned_data

            page1 = page(title = informacion['title'],subtitle = informacion['subtitle'],body = informacion['body'],author = informacion['author'],date = informacion['date'],image = informacion['image'])
            page1.save()
            return render(request,"blog_pages/leerPaginas.html")
    else:
        my_page = pageFormulario()
    
    return render(request, "blog_pages/create_page.html", {"my_page":my_page})
        

blog/login/views.py
from django.shortcuts import redirect, render
from .forms import LoginForm, UserRegisterForm
from django.contrib.auth import login, authenticate

from django.urls import reverse_lazy
from django.views.generic.edit import FormView 

def login1(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():

            username= form.cleaned_data.get('username')
            password= form.cleaned_data.get('password')

            user =authenticate(username=username, password=password)

            if user is not None:
                login(request,user)
                return render(request, 'blog_pages/inicio.html', {'mensaje': f'Bienvenido/a {user} al Blog'})
            else:
                return render(request, 'login/passornameincorrect.html', {'mensaje': 'Error, datos incorrectos'})
        else:
              return render(request, 'login/passornameincorrect.html', {'mensaje': 'Error, formulario erroneo'})  
    else:
        form = LoginForm()
    return render(request,'login/login.html', {'form': form})


def passornameincorrect(request):
    return render(request,'login/passornameincorrect.html' )

def register(request):
    if request.method == 'POST':

        form=UserRegisterForm(request.POST)
        if form.is_valid():

            username = form.cleaned_data['username']
            form.save()
            return render(request, 'blog_pages/inicio.html',{"mensaje":"Usuario creado"})
    else:
        form=UserRegisterForm()

    return render(request, 'login/registro.html', {'form':form})

blog/perfiles/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import UserUpdateForm


@login_required
def perfil(request):
    user = request.user
    context = {'user': user}
    return render(request, 'perfiles/perfil.html', context)

@login_required
def editarPerfil(request):
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile has been updated!')
            return render(request, 'perfiles/perfil.html', {'form': form})
    else:
        form = UserUpdateForm(instance=request.user)
    return render(request, 'perfiles/editarPerfil.html', {'form': form})

blog/blog_pages/templates/blog_pages/acerca_de_mi.html
{% extends "blog_pages/padre.html" %}

{% load static %}

{% block contenidoQueCambia %}
<h1>Acerca de mi:</h1>
<h2>Soy Micaela Elizabeth Gimenez</h2>
<p>Vivo en Buenos Aires Argentina y me gusta programar</p><br>
<p>Este blog trata de recetas, en el apartado "paginas" podras ver todas las recetas.</p>
</br>

<a href='{% url "blog_pages:inicio" %}' class="button">Volver</a>


{% endblock %}

blog/blog_pages/templates/blog_pages/create_page.html
{% extends "blog_pages/padre.html" %}

{% load static %}

{% block contenidoQueCambia %}
<h1>Crear Pagina:</h1>
<!-- Aqui va lo que cambia y lo asociado a esta vista -->

<form action="" method="POST">{% csrf_token %}

    <table>
        {{my_page.as_table}}
    </table>

    <input type="submit" value="Enviar">

</form>

<a href='{% url "blog_pages:leerpaginas" %}' class="button">Volver</a>


{% endblock %}

blog/blog_pages/templates/blog_pages/delete_page.html
{% extends "blog_pages/padre.html" %}

{% load static %}

{% block contenidoQueCambia %}
 <!-- Aqui va lo que cambia y lo asociado a esta vista -->
 {% if miFormulario.errors %}

 <p style="color: red;"> Estan mal los datos, revisar</p>

 {% endif %}

 <h1>Se ha eliminado la pagina...</h1>

 <form action="/leerPaginas/" method="POST">{% csrf_token %}

     <!-- Aca esta la magia de Django -->

     <table>

         {{miFormulario.as_table}}

     </table>

     <input type="submit" value="Enviar">

 </form>

<a href='{% url "blog_pages:leerpaginas" %}' class="button">Volver</a>


{% endblock %}

blog/blog_pages/templates/blog_pages/edit_page.html
{% extends "blog_pages/padre.html" %}

{% load static %}

{% block contenidoQueCambia %}
<h1>Editar Pagina:</h1>
<!-- Aqui va lo que cambia y lo asociado a esta vista -->
{% if miFormulario.errors %}

<p style="color: red;"> Estan mal los datos, revisar</p>

{% endif %}

<form method="POST">{% csrf_token %}

    <!-- Aca esta la magia de Django -->

    <table>

        {{miFormulario.as_table}}

    </table>

    <button type="submit">Guardar</button>

</form>

<a href='{% url "blog_pages:leerpaginas" %}' class="button">Volver</a>


{% endblock %}

blog/blog_pages/templates/blog_pages/inicio.html
{% extends "blog_pages/padre.html" %}

{% load static %}

{% block contenidoQueCambia %}
<br>
<br>
<br>
<br>
<nav class="navbar navbar-light bg-light static-top">
  <div class="container">
      <a class="navbar-brand" href="{% url 'blog_pages:leerpaginas' %}">Ver Paginas</a>
      <a class="navbar-brand" href="{% url 'blog_pages:acerca_de_mi' %}">Acerca de mi</a>
      <a class="navbar-brand" href="{% url 'perfiles:perfil' %}">Ver mi perfil</a>
      <a class="navbar-brand" href="{% url 'login:logout' %}">Logout</a>
  </div>
</nav>
<h1 class="visually-hidden">Blog</h1>

<div class="px-4 py-5 my-5 text-center">
  <!-- <h1 class="display-5 fw-bold">Bienvenido al blog</h1> -->
  <h1 class="display-5 fw-bold">{{mensaje}}</h1>
  <div class="col-lg-6 mx-auto">
    <h1 class="lead mb-4">Blog de contenido de recetas</h1>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
    </div>
  </div>
</div>
{% endblock %}

blog/blog_pages/templates/blog_pages/leerPaginas.html
{% extends "blog_pages/padre.html" %}

{% load static %}

{% block contenidoQueCambia %}
<a href="{% url 'blog_pages:create_page' %}">Crear Pagina</a>
{% for p in pages %}
<h1 class="visually-hidden">Blog</h1>

<div class="px-4 py-5 my-5 text-center">
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">{{p.title}}</p></br>
</br><a href='{% url "blog_pages:leer_mas" p.pk %}' class="button">Leer Mas</a>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
    </div>
  </div>
</div>
<button>
  <a href="{% url 'blog_pages:edit_page' p.title %}">Editar</a>
</button><br>
<button>
  <a href="{% url 'blog_pages:delete_page' p.title %}">Eliminar</a>
</button>
<div class="b-example-divider"></div>
{% endfor %}
</br><a href='{% url "blog_pages:inicio" %}' class="button">Volver</a>
{% endblock %}

blog/blog_pages/templates/blog_pages/leer_mas.html
{% extends "blog_pages/padre.html" %}

{% load static %}

{% block contenidoQueCambia %}

<h1 class="visually-hidden">Blog</h1>

<div class="px-4 py-5 my-5 text-center">
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">{{page.title}}</p></br>
    <p class="lead mb-4">{{page.subtitle}}</p></br>
    <p class="lead mb-4">{{page.body}}</p></br>
    <p class="lead mb-4">{{page.author}}</p></br>
    <p class="lead mb-4">{{page.date}}</p></br>
    <p><img src="{{ page.image_url|default_if_none:'#' }}" alt=""></p>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
    </div>
  </div>
</div>
<div class="b-example-divider"></div> </br>
<a href='{% url "blog_pages:leerpaginas" %}' class="button">Volver</a>
{% endblock %}

blog/blog_pages/templates/blog_pages/padre.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.108.0">
    <title>Blog</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/heroes/">

    

    

<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="css/heroes.css" rel="stylesheet">
  </head>
  <body>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<main>
  {% block contenidoQueCambia %}
  {% endblock %}

  <div class="b-example-divider"></div>

</main>


    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

      
  </body>
</html>

blog/login/templates/login/login.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.108.0">
    <title>sign-in</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/sign-in/">

    

    

<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="sign-in.css" rel="stylesheet">
  </head>
  <body class="text-center">
    
<main class="form-signin w-100 m-auto">
  <form action="" method="POST">
    {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

    <div class="form-floating">
      <label for="{{ form.username.id_for_label }}">Username: </label>
      {{ form.username }}
    </div>
    <div class="form-floating">
      <label for="{{ form.password.id_for_label }}">Password: </label>
      {{ form.password }}
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
    <a href='{% url "login:register" %}' class="button">Registrarse</a>
  </form>
</main>


    
  </body>
</html>

blog/login/templates/login/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logout</title>
</head>
<body>
    <h1>Te has deslogeado</h1></br>
    <a href='{% url "login:login" %}' class="button">Volver al login</a>
</body>
</html>

blog/login/templates/login/passornameincorrect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
</head>
<body>
    <h1>El password o el username son incorrectos</h1> </br>
    <a href='{% url "login:login" %}' class="button">Volver</a>
</body>
</html>

blog/perfiles/templates/perfiles/perfil.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.108.0">
    <title>Blog</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/heroes/">

    

    

<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="css/heroes.css" rel="stylesheet">
  </head>
  <body>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<main>
  {% csrf_token %}
  <h1 class="visually-hidden">Datos</h1>

<div class="px-4 py-5 my-5 text-center">
  <h1 class="display-5 fw-bold">Datos de tu perfil</h1>
  <div class="col-lg-6 mx-auto">
    <p>Username: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p></br>
    <a href="{% url 'perfiles:editarPerfil' %}">Editar Perfil</a></br>
    <a href='{% url "blog_pages:inicio" %}' class="button">Volver al home</a>

    <p class="lead mb-4"></p>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
    </div>
  </div>
</div>

  <div class="b-example-divider"></div>

</main>


    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

      
  </body>
</html>